### ISSUE TITLE
organisation-config.js nog nodig

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/NL-ReSpec-GN-template#2]
In index.html wordt nu verwezen naar geen organisation-config.js die op tools.geostandaarden.nl staat. Is het dan niet verwarrend dat er ook nog een organisation-config.js lokaal staat die dus niks doet?

**Comment by lvdbrink** [comment]
Goed punt, dat is verwarrend. We moeten wel ergens de organisation-config.js beheren. Is er al een github repo die daar een logische plek voor is?

**Comment by wilkoquak** [comment]
Dat zou dan in hetzelfde repository kunnen waarin we onze logo's en bibliografie beheren. Maar ik gok zomaar eens dat die ook nog ergens moeten landen. Zullen we er maar een repo voor aanmaken @Geonovum/respec-beheer bijvoorbeeld NL-ReSpec-GN-beheer

**Comment by lvdbrink** [comment]
Ja, goed idee!

**Comment by wilkoquak** [comment]
Bij deze (https://github.com/Geonovum/NL-ReSpec-GN-beheer) . Nu moet iemand het bestand nog overzetten.
