### ISSUE TITLE
favicon nog niet van Geonovum

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/NL-ReSpec-GN-template#3]
Het favicon van de Geonovum pagina's is nog steeds het rijkslogo. Hier zou een Geonovum logo moeten staan,
![afbeelding](https://github.com/Geonovum/NL-ReSpec-GN-template/assets/2814052/af82694b-f00a-4244-a358-a22cc7d239f4)

**Comment by lvdbrink** [comment]
Bij mij gaat dit wel goed. 

![favicon](https://github.com/Geonovum/NL-ReSpec-GN-template/assets/7943515/cbc911b0-9ee7-45cf-a4c4-fa573964cc97)

Het favicon is niet configureerbaar, het moet in de header van je index.html staan. In de index.html van deze template repo staat dit er ook (laatste `<link>` element): 

```
<head>
  <meta content="text/html; charset=utf-8" http-equiv="content-type">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://cdn.jsdelivr.net/gh/digitalbazaar/respec-mermaid@1.0.1/dist/main.js" class="remove"></script>
  <script src="https://tools.geostandaarden.nl/respec/config/geonovum-config.js" class="remove"></script>
  <script src="js/config.js" class="remove"></script>
  <script class="remove"> respecConfig = {...organisationConfig, ...respecConfig}</script>
  <script>document.title = respecConfig.title</script>
  <title>Default</title>
  <link rel="shortcut icon" type="image/x-icon" href="https://tools.geostandaarden.nl/respec/style/logos/Geonovum.ico" />
  <script src="https://gitdocumentatie.logius.nl/publicatie/respec/builds/respec-nlgov.js" class="remove" async></script>
</head>
```

**Comment by wilkoquak** [comment]
Oh ik zie het. Blijkbaar heb ik voor mijn repository te lang geleden de template gebruikt want nu gaat het goed.
