### ISSUE TITLE
Het automatisch builden van de snapshots werkt niet meer

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/NL-ReSpec-GN-template#4]
Één van de leuke dingen van de nieuwe template is dat er automatisch een snapsot en pdf wordt aangemaakt. Maar sinds een week of drie werkt dat niet meer. Met een beetje puzzelen denk ik dat te traceren tot een nieuwe build.yml die bij Logius staat. Maar een fix durf ik nog even niet aan. Is er iemand dit dit weer aan de praat kan krijgen?

**Comment by lvdbrink** [comment]
Niet bij Geonovum; je kan bij Logius wel een PR doen of een issue aanmaken om dit opgelost te krijgen. Contactpersoon daar is @sanderke.

**Comment by sanderke** [comment]
Het was mij ontgaan dat ook de GitHuB Actions extrern gebruikt kunnen worden. Wel leuk om te zien en de functionaliteit van drie weken geleden kan hersteld worden met deze kleine aanpassing:
https://github.com/Logius-standaarden/ReSpec-template/commit/1196f940d227732b08056dd405abb39d7ca05978
