### ISSUE TITLE
Imvertor maakt Image maps aan maar die gaan niet goed samen met geschaalde images

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/NL-ReSpec-GN-template#5]
Bij het maken van een Catalogus maakt imvertor Image Maps aan waardoor je op een klasse in een UML diagram kan klikken en automatisch doorspringt naar de definitie van die klasse.  Alleen in de nieuwe ReSpec omgeving worden de plaatjes af en toe geschaald. Maar de Image Map niet waardoor het doorspringen naar de definite niet meer werkt.

**Comment by wilkoquak** [comment]
Een oplossing waarin de coördinaten in een imagemap worden meegeschaald is niet haalbaar. Daarom is de meest logische oplossing om er via de stylesheet voor te zorgen dat op zijn minst de UML diagrammen niet geschaald worden. Wat vinden jullie van deze oplossing @lvdbrink @gwolbers ? En wie heeft de know-how om dit te implementeren?

**Comment by gwolbers** [comment]
Hoi Wilko,

Volgens mij hebben we deze oplossing in een eerder bestand van Michel Grothe gebruikt. We zijn hier in ieder geval eerder mee bezig geweest. Moet ik terugzoeken in de mails.


Met vriendelijke groet,



Gerard Wolbers

**Comment by wilkoquak** [comment]
@gwolbers klopt . In in het wijzigingsprotocol van IMGeluid zit ook een plaatje dat te groot is (https://geonovum.github.io/IMG-wijzigingsprotocol/#het-wijzigingsproces-in-detail) voor het tekstveld. In dit geval wordt per default nog wel de geschaalde versie getoond maar als je erop klikt verschijnt de ongeschaalde versie.  Zoiets, maar dan net anders, moet dus met plaatjes gebeuren waar een imagemap bij zit. Ik ga (voor NA je vakantie) dit issue aan je toekennen, mocht je er niet uitkomen geef dan maar weer terug aan mij...

**Comment by gwolbers** [comment]
Ken maar aan me toe. Komt goed.


Met vriendelijke groet,



Gerard

**Comment by wilkoquak** [comment]
Dit is wat mij betreft wel een belangrijk issue dat het echt publiceren van UML in de nieuwe ReSpec omgeving in de weg staat. Zo ziet https://geonovum.github.io/dso-cim-ow/ er best strak uit, maar die imagemaps werken nog niet. Welke stappen zijn nodig om dit issue op te lossen?

**Comment by gwolbers** [comment]
Hoi Wilko,

Veruit bij voorkeur worden de imagemaps geëxporteerd naar svg. Binnen de svg kun je een url koppelen aan elk ingesloten object. Als het interne formaat van zo'n uml-plaatje gebaseerd is op een xml-formaat, dan kunnen we dit zelf naar svg omzetten.


Met vriendelijke groet,



Gerard Wolbers

______________________________________

Geonovum

Senior beheerder geo-informatiestandaarden



a: Barchman Wuytierslaan 10, 3818 LH Amersfoort

p: Postbus 508, 3800 AM Amersfoort

m:+ 31 (0)6 54955047 (direct)

t:+ 31 (0)33 4604100 (algemeen)

e: ***@***.******@***.***>

i: www.geonovum.nl<http://www.geonovum.nl>



________________________________
Van: Wilko Quak ***@***.***>
Verzonden: vrijdag 29 september 2023 10:11
Aan: Geonovum/NL-ReSpec-GN-template ***@***.***>
CC: Gerard Wolbers ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Geonovum/NL-ReSpec-GN-template] Imvertor maakt Image maps aan maar die gaan niet goed samen met geschaalde images (Issue #5)


Dit is wat mij betreft wel een belangrijk issue dat het echt publiceren van UML in de nieuwe ReSpec omgeving in de weg staat. Zo ziet https://geonovum.github.io/dso-cim-ow/ er best strak uit, maar die imagemaps werken nog niet. Welke stappen zijn nodig om dit issue op te lossen?

**Comment by wilkoquak** [comment]
De oplossing bestaat eruit dat Imvertor om alle `<figure>` element een class `<div class="imageinfo">` neerzet. Door nu in de laatste regel van de header van `index.html` de volgende regel op te nemen `<style>div.imageinfo.overview img {max-width: none;}</style>` worden de Imvertor plaatjes niet meer geschaald.
