### ISSUE TITLE
De standaardtekst voor het conformance hoofdstuk is niet duidelijk

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/NL-ReSpec-GN-template#7]
Zie screenshot. Waarom zijn diagrammen en voetnoten niet normatief? En zie ik in het onderstaande plaatje nu een diagram (zoals de titel van het hoofdstuk zegt) of een figuur (zoals de caption zegt). 

Ik zie sowieso niet in wat dit hoofdstuk doet.

![afbeelding](https://github.com/Geonovum/NL-ReSpec-GN-template/assets/2814052/07ec3575-d83a-44eb-a8a7-6730d27ae8de)

**Comment by lvdbrink** [comment]
Het zat in de oorspronkelijke template van Logius, denk ik. Het lijkt mij prima om het weg te laten / weg te halen uit ons template. Enige wat nog zou kunnen is dat ReSpec het vereist voor bepaalde documenttypen, maar daar zou je al snel achter komen als je het weg laat.
